[workspace]
resolver = "2"
members = ["cli", "core", "runtime"]


[workspace.dependencies]
clap = { version = "4.5.9", features = ["derive"] }
cliclack = "0.3.2"
console = "0.15.8"
miette = { version = "7.2.0", features = ["fancy"] }
nova_vm = { git = "https://github.com/trynova/nova", rev = "679a0e1bb0b5601936ab5885df154d9c536650be", features = ["typescript"] }
oxc_ast = "0.20.0"
oxc_parser = "0.20.0"
oxc_span = "0.20.0"
oxc_diagnostics = "0.20.0"
oxc_semantic = "0.20.0"
andromeda-core = { path = "core" }
andromeda-runtime = { path = "runtime" }
anymap = "0.12.1"
tokio = { version = "1.39.0", features = ["full"]}
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
