[workspace]
resolver = "2"
members = ["cli", "core", "runtime"]


[workspace.dependencies]
clap = { version = "4.5.9", features = ["derive"] }
cliclack = "0.3.2"
console = "0.15.8"
miette = { version = "7.2.0", features = ["fancy"] }
nova_vm = { git = "https://github.com/load1n9/nova", branch="array-from-slice", features = ["typescript"] }
oxc_ast = "0.20.0"
oxc_parser = "0.20.0"
oxc_span = "0.20.0"
oxc_diagnostics = "0.20.0"
oxc_semantic = "0.20.0"
andromeda-core = { path = "core" }
andromeda-runtime = { path = "runtime" }
anymap = "0.12.1"
tokio = { version = "1.39.0", features = ["rt", "sync", "time"]}
