[workspace]
resolver = "2"
members = ["cli", "core"]


[workspace.dependencies]
clap = { version = "4.5.9", features = ["derive"] }
cliclack = "0.3.2"
console = "0.15.8"
miette = { version = "7.2.0", features = ["fancy"] }
nova_vm = { path = "../nova/nova_vm", features = ["typescript"] }
oxc_ast = "0.20.0"
oxc_parser = "0.20.0"
oxc_span = "0.20.0"
oxc_diagnostics = "0.20.0"
oxc_allocator = "0.20.0"
oxc_semantic = "0.20.0"
andromeda-core = { path = "core" }
anymap = "0.12.1"
tokio = { version = "1.39.0", features = ["rt", "sync", "time"]}
