[package]
name = "andromeda"
version = "0.1.0"
edition = "2021"
default-run = "andromeda"
license = "MIT"
readme = "../README.md"

[features]
default = []

[dependencies]
clap = { workspace = true }
cliclack = { workspace = true }
console = { workspace = true }
nova_vm = { workspace = true }
andromeda-core = { workspace = true }
oxc_ast = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }
oxc_allocator = { workspace = true }
oxc_semantic = { workspace = true }
anymap = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
